apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-heap-dump-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-heap-dump-app
  template:
    metadata:
      labels:
        app: java-heap-dump-app
    spec:
      containers:
      - name: java-heap-dump
        image: mkhairulfaizi3/heap-dump-generator:d4c2d5055eb526b71c2adf4881c8d92f88701dde
        command: ["java"]
        args: ["-XX:+HeapDumpOnOutOfMemoryError", "-XX:HeapDumpPath=/heap-dumps", "-Xmx512m", "-jar", "/app/app.jar"]
        volumeMounts:
        - name: heap-dump-volume
          mountPath: /heap-dumps
        ports:
        - containerPort: 8080
      volumes:
      - name: heap-dump-volume
        persistentVolumeClaim:
          claimName: heap-dump-pvc
